In [1]:
import pandas as pd 
data= {'Tid': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'Refund': ["yes","no","no","yes","no","no","yes","no","no","no"],
         'Martial Status': ["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
        'Taxable Income': ['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k'],
         'Cheat': ["no","no","no","no","yes","no","no","yes","no","yes"]}
df=pd.DataFrame(data)
print(df)

   Tid Refund Martial Status Taxable Income Cheat
0    1    yes         Single           125k    no
1    2     no        Married           100k    no
2    3     no         Single            70k    no
3    4    yes        Married           120k    no
4    5     no       Divorced            95k   yes
5    6     no        Married            60k    no
6    7    yes       Divorced           220k    no
7    8     no         Single            85k   yes
8    9     no        Married            75k    no
9   10     no         Single            90k   yes

In [2]:
df.iloc[[0,4,7,8]]

   Tid Refund Martial Status Taxable Income Cheat
0    1    yes         Single           125k    no
4    5     no       Divorced            95k   yes
7    8     no         Single            85k   yes
8    9     no        Married            75k    no

In [3]:
df.iloc[[3,7]]

   Tid Refund Martial Status Taxable Income Cheat
3    4    yes        Married           120k    no
7    8     no         Single            85k   yes

In [4]:
df.iloc[4:8, 2:4]

  Martial Status Taxable Income
4       Divorced            95k
5        Married            60k
6       Divorced           220k
7         Single            85k

In [5]:
df.iloc[:, [1, 2, 3]]

  Refund Martial Status Taxable Income
0    yes         Single           125k
1     no        Married           100k
2     no         Single            70k
3    yes        Married           120k
4     no       Divorced            95k
5     no        Married            60k
6    yes       Divorced           220k
7     no         Single            85k
8     no        Married            75k
9     no         Single            90k

In [6]:
daf = pd.read_csv("C:/Users/HP/Downloads/archive/Iris.csv")
daf.iloc[[1,2,3,4,5]]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [7]:
daf = daf.drop(columns=['SepalWidthCm']) 
daf=daf.drop(index=[4])
print(daf.to_string())

      Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
0      1            5.1            1.4           0.2      Iris-setosa
1      2            4.9            1.4           0.2      Iris-setosa
2      3            4.7            1.3           0.2      Iris-setosa
3      4            4.6            1.5           0.2      Iris-setosa
5      6            5.4            1.7           0.4      Iris-setosa
6      7            4.6            1.4           0.3      Iris-setosa
7      8            5.0            1.5           0.2      Iris-setosa
8      9            4.4            1.4           0.2      Iris-setosa
9     10            4.9            1.5           0.1      Iris-setosa
10    11            5.4            1.5           0.2      Iris-setosa
11    12            4.8            1.6           0.2      Iris-setosa
12    13            4.8            1.4           0.1      Iris-setosa
13    14            4.3            1.1           0.1      Iris-setosa
14    15            5.8            1.2           0.2      Iris-setosa
15    16            5.7            1.5           0.4      Iris-setosa
16    17            5.4            1.3           0.4      Iris-setosa
17    18            5.1            1.4           0.3      Iris-setosa
18    19            5.7            1.7           0.3      Iris-setosa
19    20            5.1            1.5           0.3      Iris-setosa
20    21            5.4            1.7           0.2      Iris-setosa
21    22            5.1            1.5           0.4      Iris-setosa
22    23            4.6            1.0           0.2      Iris-setosa
23    24            5.1            1.7           0.5      Iris-setosa
24    25            4.8            1.9           0.2      Iris-setosa
25    26            5.0            1.6           0.2      Iris-setosa
26    27            5.0            1.6           0.4      Iris-setosa
27    28            5.2            1.5           0.2      Iris-setosa
28    29            5.2            1.4           0.2      Iris-setosa
29    30            4.7            1.6           0.2      Iris-setosa
30    31            4.8            1.6           0.2      Iris-setosa
31    32            5.4            1.5           0.4      Iris-setosa
32    33            5.2            1.5           0.1      Iris-setosa
33    34            5.5            1.4           0.2      Iris-setosa
34    35            4.9            1.5           0.1      Iris-setosa
35    36            5.0            1.2           0.2      Iris-setosa
36    37            5.5            1.3           0.2      Iris-setosa
37    38            4.9            1.5           0.1      Iris-setosa
38    39            4.4            1.3           0.2      Iris-setosa
39    40            5.1            1.5           0.2      Iris-setosa
40    41            5.0            1.3           0.3      Iris-setosa
41    42            4.5            1.3           0.3      Iris-setosa
42    43            4.4            1.3           0.2      Iris-setosa
43    44            5.0            1.6           0.6      Iris-setosa
44    45            5.1            1.9           0.4      Iris-setosa
45    46            4.8            1.4           0.3      Iris-setosa
46    47            5.1            1.6           0.2      Iris-setosa
47    48            4.6            1.4           0.2      Iris-setosa
48    49            5.3            1.5           0.2      Iris-setosa
49    50            5.0            1.4           0.2      Iris-setosa
50    51            7.0            4.7           1.4  Iris-versicolor
51    52            6.4            4.5           1.5  Iris-versicolor
52    53            6.9            4.9           1.5  Iris-versicolor
53    54            5.5            4.0           1.3  Iris-versicolor
54    55            6.5            4.6           1.5  Iris-versicolor
55    56            5.7            4.5           1.3  Iris-versicolor
56    57            6.3            4.7           1.6  Iris-versicolor
57    58            4.9            3.3           1.0  Iris-versicolor
58    59            6.6            4.6           1.3  Iris-versicolor
59    60            5.2            3.9           1.4  Iris-versicolor
60    61            5.0            3.5           1.0  Iris-versicolor
61    62            5.9            4.2           1.5  Iris-versicolor
62    63            6.0            4.0           1.0  Iris-versicolor
63    64            6.1            4.7           1.4  Iris-versicolor
64    65            5.6            3.6           1.3  Iris-versicolor
65    66            6.7            4.4           1.4  Iris-versicolor
66    67            5.6            4.5           1.5  Iris-versicolor
67    68            5.8            4.1           1.0  Iris-versicolor
68    69            6.2            4.5           1.5  Iris-versicolor
69    70            5.6            3.9           1.1  Iris-versicolor
70    71            5.9            4.8           1.8  Iris-versicolor
71    72            6.1            4.0           1.3  Iris-versicolor
72    73            6.3            4.9           1.5  Iris-versicolor
73    74            6.1            4.7           1.2  Iris-versicolor
74    75            6.4            4.3           1.3  Iris-versicolor
75    76            6.6            4.4           1.4  Iris-versicolor
76    77            6.8            4.8           1.4  Iris-versicolor
77    78            6.7            5.0           1.7  Iris-versicolor
78    79            6.0            4.5           1.5  Iris-versicolor
79    80            5.7            3.5           1.0  Iris-versicolor
80    81            5.5            3.8           1.1  Iris-versicolor
81    82            5.5            3.7           1.0  Iris-versicolor
82    83            5.8            3.9           1.2  Iris-versicolor
83    84            6.0            5.1           1.6  Iris-versicolor
84    85            5.4            4.5           1.5  Iris-versicolor
85    86            6.0            4.5           1.6  Iris-versicolor
86    87            6.7            4.7           1.5  Iris-versicolor
87    88            6.3            4.4           1.3  Iris-versicolor
88    89            5.6            4.1           1.3  Iris-versicolor
89    90            5.5            4.0           1.3  Iris-versicolor
90    91            5.5            4.4           1.2  Iris-versicolor
91    92            6.1            4.6           1.4  Iris-versicolor
92    93            5.8            4.0           1.2  Iris-versicolor
93    94            5.0            3.3           1.0  Iris-versicolor
94    95            5.6            4.2           1.3  Iris-versicolor
95    96            5.7            4.2           1.2  Iris-versicolor
96    97            5.7            4.2           1.3  Iris-versicolor
97    98            6.2            4.3           1.3  Iris-versicolor
98    99            5.1            3.0           1.1  Iris-versicolor
99   100            5.7            4.1           1.3  Iris-versicolor
100  101            6.3            6.0           2.5   Iris-virginica
101  102            5.8            5.1           1.9   Iris-virginica
102  103            7.1            5.9           2.1   Iris-virginica
103  104            6.3            5.6           1.8   Iris-virginica
104  105            6.5            5.8           2.2   Iris-virginica
105  106            7.6            6.6           2.1   Iris-virginica
106  107            4.9            4.5           1.7   Iris-virginica
107  108            7.3            6.3           1.8   Iris-virginica
108  109            6.7            5.8           1.8   Iris-virginica
109  110            7.2            6.1           2.5   Iris-virginica
110  111            6.5            5.1           2.0   Iris-virginica
111  112            6.4            5.3           1.9   Iris-virginica
112  113            6.8            5.5           2.1   Iris-virginica
113  114            5.7            5.0           2.0   Iris-virginica
114  115            5.8            5.1           2.4   Iris-virginica
115  116            6.4            5.3           2.3   Iris-virginica
116  117            6.5            5.5           1.8   Iris-virginica
117  118            7.7            6.7           2.2   Iris-virginica
118  119            7.7            6.9           2.3   Iris-virginica
119  120            6.0            5.0           1.5   Iris-virginica
120  121            6.9            5.7           2.3   Iris-virginica
121  122            5.6            4.9           2.0   Iris-virginica
122  123            7.7            6.7           2.0   Iris-virginica
123  124            6.3            4.9           1.8   Iris-virginica
124  125            6.7            5.7           2.1   Iris-virginica
125  126            7.2            6.0           1.8   Iris-virginica
126  127            6.2            4.8           1.8   Iris-virginica
127  128            6.1            4.9           1.8   Iris-virginica
128  129            6.4            5.6           2.1   Iris-virginica
129  130            7.2            5.8           1.6   Iris-virginica
130  131            7.4            6.1           1.9   Iris-virginica
131  132            7.9            6.4           2.0   Iris-virginica
132  133            6.4            5.6           2.2   Iris-virginica
133  134            6.3            5.1           1.5   Iris-virginica
134  135            6.1            5.6           1.4   Iris-virginica
135  136            7.7            6.1           2.3   Iris-virginica
136  137            6.3            5.6           2.4   Iris-virginica
137  138            6.4            5.5           1.8   Iris-virginica
138  139            6.0            4.8           1.8   Iris-virginica
139  140            6.9            5.4           2.1   Iris-virginica
140  141            6.7            5.6           2.4   Iris-virginica
141  142            6.9            5.1           2.3   Iris-virginica
142  143            5.8            5.1           1.9   Iris-virginica
143  144            6.8            5.9           2.3   Iris-virginica
144  145            6.7            5.7           2.5   Iris-virginica
145  146            6.7            5.2           2.3   Iris-virginica
146  147            6.3            5.0           1.9   Iris-virginica
147  148            6.5            5.2           2.0   Iris-virginica
148  149            6.2            5.4           2.3   Iris-virginica
149  150            5.9            5.1           1.8   Iris-virginica

In [8]:
dat={
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Edward'],
    'Department': ['HR','IT','IT','Marketing','Sales'],
    'Age': [29, 34, 41, 28, 38],
    'Salary': [50000, 70000, 65000, 55000, 60000],
    'Years_of_Experience': [4, 8, 10, 3, 12],
    'Joining_Date': ['2020-03-15', '2017-07-19', '2013-06-01', '2021-02-10','2010-11-25'],
    'Gender': ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    'Rating': [4.5, 4.0, 3.8, 4.7, 3.5]}
d=pd.DataFrame(dat)
print(d)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [10]:
print(d.shape)
print(df.info())
print(df.describe())

(5, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Tid             10 non-null     int64
 1   Refund          10 non-null     object
 2   Martial Status  10 non-null     object
 3   Taxable Income  10 non-null     object
 4   Cheat           10 non-null     object
dtypes: int64(1), object(4)
memory usage: 532.0+ bytes
None
            Tid
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

In [11]:
print(df.head(5))
print(df.tail(3))

   Tid Refund Martial Status Taxable Income Cheat
0    1    yes         Single           125k    no
1    2     no        Married           100k    no
2    3     no         Single            70k    no
3    4    yes        Married           120k    no
4    5     no       Divorced            95k   yes
   Tid Refund Martial Status Taxable Income Cheat
7    8     no         Single            85k   yes
8    9     no        Married            75k    no
9   10     no         Single            90k   yes

In [12]:
a= d['Salary'].mean()
t= d['Bonus'].sum()
y= d['Age'].min()
h= d['Rating'].max()

print("Average Salary:", a)
print("Total Bonus:", t)
print("Youngest Employee's Age:", y)
print("Highest Rating:", h)

Average Salary: 60000.0
Total Bonus: 27500
Youngest Employee's Age: 28
Highest Rating: 4.7

In [13]:
d_sorted = d.sort_values(by='Salary', ascending=False)
print(d_sorted)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [14]:
def categorize(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    else:
        return 'Average'
d['Performance_Category'] = d['Rating'].apply(categorize)
print(d)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance_Category
0   2020-03-15  Female   5000     4.5            Excellent
1   2017-07-19    Male   7000     4.0                 Good
2   2013-06-01    Male   6000     3.8              Average
3   2021-02-10  Female   4500     4.7            Excellent
4   2010-11-25    Male   5000     3.5              Average

In [15]:
print(d.isnull().sum())
print("\n     ")
d = d.rename(columns={'Employee_ID': 'ID'})
print(d.columns)
print("\n     ")
m= d[d['Years_of_Experience'] > 5]
it= d[d['Department'] == 'IT']
print(m)
print(it)

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64


Index(['ID', 'Name', 'Department', 'Age', 'Salary', 'Years_of_Experience',
       'Joining_Date', 'Gender', 'Bonus', 'Rating', 'Performance_Category'],
      dtype='object')


    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average
4   Male   5000     3.5              Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average

In [16]:
d['Tax'] = d['Salary'] * 0.10
print(d)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance_Category     Tax
0  Female   5000     4.5            Excellent  5000.0
1    Male   7000     4.0                 Good  7000.0
2    Male   6000     3.8              Average  6500.0
3  Female   4500     4.7            Excellent  5500.0
4    Male   5000     3.5              Average  6000.0

In [17]:
d.to_csv('employees_modified.csv', index=False)